### ISSUE TITLE
Background and cursor not changing during drag

### ISSUE THREAD

**Issue by jpeterbaker** [dragon76n/greasemonkey#1]
Lines 53-54 are intended to make the cursor and background change while dragging. They should be modifying the style of `myForm` rather than `elementDrag`.

Also, the background should probably change back after dragging for readability. I'm not so sure how to do that.

**Comment by dragon76n** [comment]
Thanks. The color change wasn't intended, but I did want the cursor to change. I've removed unnecessary color changing code and fixed cursor changing for mousedown and mouseup.
